merge_lidar_node:
  ros__parameters:
    sync_frequency: 20.0
    slice_z_min: -2.0
    slice_z_max: 2.0

    lidars.topics:
      - "/livox/lidar_192_168_2_102"   # lidar_0 = livox_front
      - "/livox/lidar_192_168_3_144"   # lidar_1 = livox_rear
      # livox_top(192.168.1.135)은 병합에 넣지 않는다. IMU만 쓴다.

    lidars.extrinsics.lidar_0:   # base_footprint <- livox_front  (예전 static TF)
      - 0.000000
      - -1.000000
      - 0.000000
      - 0.697000        # ---
      - 1.000000
      - 0.000000
      - 0.000000
      - 0.350000        # ---
      - 0.000000
      - 0.000000
      - 1.000000
      - -0.180000        # ---
      - 0.000000
      - 0.000000
      - 0.000000
      - 1.000000


    lidars.extrinsics.lidar_1:   # base_footprint <- livox_rear   (예전 static TF)
      - 0.000000
      - 1.000000
      - 0.000000
      - -0.600000        # ---
      - -1.000000
      - 0.000000
      - 0.000000
      - -0.340000        # ---
      - 0.000000
      - 0.000000
      - 1.000000
      - -0.180000        # ---
      - 0.000000
      - 0.000000
      - 0.000000
      - 1.000000


    output.pointcloud2: "/livox_merge/merged_pointcloud"
    output.livox_custom: "/livox_merge/merged_livox"
    output.pointcloud2_sliced: "/livox_merge/merged_pointcloud_sliced"
    output.frame_id: "base_footprint"   # 위 extrinsic 이 실제로 보내는 프레임
