<?xml version="1.0"?>
<package format="3">
  <name>pointcloud2_to_custommsg</name>
  <version>0.0.1</version>
  <description>Convert PointCloud2 to livox custom msg</description>

  <maintainer email="you@example.com">you</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>livox_ros_driver2</depend>
  <depend>pcl_conversions</depend>

  <exec_depend>pcl_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
